<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DeskTown.Application/DeskTown.Application.csproj" />
    <ProjectReference Include="../../src/DeskTown.Domain/DeskTown.Domain.csproj" />
    <ProjectReference Include="../../src/DeskTown.Persistence/DeskTown.Persistence.csproj" />
  </ItemGroup>
</Project>
